version: '3'

services:
  node1:
    image: blastbeng/meteorcoin
    container_name: meteortest-node1
    volumes:
      - ../meteorcoind:/var/lib/meteorcoind/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: blastbeng/meteorcoin
#    container_name: meteortest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: blastbeng/meteorcoin
#    container_name: meteortest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

