version: '3'

services:
  node1:
    image: blastbeng/ecommercecoin
    container_name: ecommercetest-node1
    volumes:
      - ../ecommercecoind:/var/lib/ecommercecoind/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: blastbeng/ecommercecoin
#    container_name: ecommercetest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: blastbeng/ecommercecoin
#    container_name: ecommercetest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

